; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Click2Folders"
#define MyAppVersion "1.1"
#define MyAppPublisher "German Vargas"
#define MyAppURL "http://www.click2folders.com/"
#define MyAppExeName "click2folders.exe"

[Setup]
AppId={{E5F6D789-ABCD-4567-8901-23456789ABCD}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Usuario\Desktop\click2folder\license.txt
OutputDir=C:\Users\Usuario\Desktop\click2folder\output
OutputBaseFilename=Click2Folders_Installer
SetupIconFile=C:\Users\Usuario\Desktop\click2folder\favicon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\favicon.ico

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Usuario\Desktop\click2folder\dist\click2folders.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\click2folder\license.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\click2folder\favicon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\favicon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\favicon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
; Asegurar que la carpeta 'data' se cree con permisos completos para todos los usuarios
Name: "{app}\data"; Permissions: everyone-full

[UninstallDelete]
Type: filesandordirs; Name: "{app}\data"